debug: true

# Database configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: Ameena
    driver-class-name: com.mysql.cj.jdbc.Driver

# JPA configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
